server.port=9090

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/stat
spring.datasource.username=stat
spring.datasource.password=stat

#spring.config.activate.on-profile=test
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.url=jdbc:h2:mem:stat
#spring.datasource.username=stat
#spring.datasource.password=stat